name: Submit to Kodi Repo

on:
  push:
    tags:
      - '*'

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Insert API tokens
        run: |
          sed -i s/%apikey%/${{ secrets.API_KEY }}/ metadata.movies.thetvdb.com.v4.python/resources/lib/tvdb.py
          sed -i s/%apikey_with_pin%/${{ secrets.API_KEY_WITH_PIN}}/ metadata.movies.thetvdb.com.v4.python/resources/lib/tvdb.py
          cat metadata.movies.thetvdb.com.v4.python/resources/lib/tvdb.py

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install addon checker
        run: |
          pip install -q kodi-addon-checker

      - name: Check with addon-checker
        run: |
          kodi-addon-checker --branch matrix

#      - name: Install addon submitter
#        run: |
#          pip install -q git+https://github.com/xbmc/kodi-addon-submitter.git
#
#      - name: Submit addon
#        run: |
#          submit-addon -r repo-scrapers -b matrix -s --pull-request metadata.movies.thetvdb.com.v4.python
#        env:
#          GH_USERNAME: tvdb-kodi-ci
#          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#          EMAIL: thetvdb@thetvdb.com
